val of_sharkdown :
  ?concrete_paths:(string * Fpath.t) list -> string -> Shark_ast.Ast.t * string
(** [of_sharkdown] takes in the sharkdown document and generates and AST. If the frontmatter contains
    declarations of external inputs they can be overridden by supplying [concerte_paths] that maps the input
    name to a file path. In addition to the AST the sharkdown document is returned, with the body section
    being updated for any autogenerated blocks. *)
